### ISSUE TITLE
Error: "Could not find commit hash for master"

### ISSUE THREAD

**Issue by docmars** [Rich-Harris/degit#37] opened 2018-10-04 02:36 UTC
Hey there—I'm trying to get started with **Svelte** and running:

**Environment:**
- macOS 10.14 Mojave
- Node v8.11.4
- degit v2.1.3

Running:
```bash
degit sveltejs/template-webpack
```
... gives me:
```
! could not find commit hash for master
```

Double checking that the `user/repo` is correct, I'm not really sure why it can't find the hash. I tried it with a couple other repos out there and no-go.

Any ideas?

**Comment by docmars** [comment] 2018-10-04 03:34
Well derp, I was trying to run this on a new Macbook Pro that I hadn't installed Xcode or the Command Line Tools on, so `git` wasn't ready to go yet. Now that it's installed, I tried `degit` again and everything worked like a charm.

It may be pertinent in the rare cases when people don't have `git` properly configured (_who even does that?!_) that `degit` properly pass any errors along that may occur like this.

**Comment by paulocoghi** [comment] 2018-10-12 18:59
Would be interesting if `degit` doesn't depend on `git` to work. I was trying to figure out for weeks why some team mates had the same issue. :smile:

**Comment by Webzeugmacher** [comment] 2018-11-24 14:53
git update helped on windows 10

**Comment by oliverjanik** [comment] 2018-12-30 02:43
I just updated to latest git on Win 10 same problem:
```
PS C:\Users\Oliver\dev> degit svetlejs/template svetle-test
! could not find commit hash for master
```

Any more ideas?

**Comment by docmars** [comment] 2018-12-30 17:33
@oliverjanik Could you make sure `git` is on your PATH (or at least usable with the `git` command in your prompt?) It's possible you need to relink it after updating or installing.

**Comment by osdevisnot** [comment] 2019-04-03 21:19
This error manifests itself in Travis CI too. Trying to use `degit` there currently results in this error:

```
(node:5343) UnhandledPromiseRejectionWarning: Error: could not find commit hash for master
    at Degit.clone (/home/travis/build/osdevisnot/tslib-cli/node_modules/degit/index.js:170:10)
    at Object.<anonymous> (/home/travis/build/osdevisnot/tslib-cli/cli.js:39:15)
    at Module._compile (internal/modules/cjs/loader.js:701:30)
    at Object.Module._extensions..js (internal/modules/cjs/loader.js:712:10)
    at Module.load (internal/modules/cjs/loader.js:600:32)
    at tryModuleLoad (internal/modules/cjs/loader.js:539:12)
    at Function.Module._load (internal/modules/cjs/loader.js:531:3)
    at Function.Module.runMain (internal/modules/cjs/loader.js:754:12)
    at startup (internal/bootstrap/node.js:283:19)
    at bootstrapNodeJSCore (internal/bootstrap/node.js:622:3)
```

**Comment by DerBasler** [comment] 2019-05-11 11:48
I had the same problem using it in my wsl shell but had no problem using it in my powershell. 
I was using git version 2.11.0 in my powershell and 1.9.1 in my wsl. Maybe that helps someone.

**Comment by paulocoghi** [comment] 2019-05-11 12:04
I replaced **degit** with **[`lukeed/gittar`](https://github.com/lukeed/gittar)**, and it's sufficient for what I need.

It isn't a pure replacement, and maybe doesn't have all the features you are using on degit, but it can suit most use cases.

**Comment by paulocoghi** [comment] 2019-05-11 12:10
@docmars , @Rich-Harris 

I think we can close this issue, because I don't think anymore that it would be the case to adapt degit to don't depend on git, because it's exactly what [gittar](https://github.com/lukeed/gittar) does.

We can live with both libraries, each one with its pros and cons.

Degit has more features, but requires git. Degit is more simple, but doesn't requires git. Each developer chooses the one it sees fit.

**Comment by osdevisnot** [comment] 2019-05-13 19:39
Agree with @paulocoghi here. For my small project I ended up using gittar as well.

**Comment by bigidea-kz** [comment] 2019-05-22 08:36
maybe you need to write about it in the documentation?

**Comment by cogoo** [comment] 2019-05-22 18:59
Setting the cache value to false in the degit options solved this for me:

```
degit(repo, {
      cache: false,
      force: true,
      verbose: true,
    });
```

**Comment by paulocoghi** [comment] 2019-05-23 17:03
@cogoo, in the most cases, this error occurs when `git` isn't available/installed.

**Comment by cogoo** [comment] 2019-05-23 17:06
> @cogoo, in the most cases, this error occurs when `git` isn't available/installed.

I have `git` installed. With `cache: true` it attempts to find the repo from a local cache, which is what caused the error for me

**Comment by jspinella** [comment] 2019-06-08 00:14
Thanks for saving me some time on this one... same situation, just did a phresh install with Catalina. You'd think the error message would be a little more... helpful.

**Comment by riazXrazor** [comment] 2019-09-28 14:27
thanks @cogoo it worked !!

**Comment by vguhesan** [comment] 2019-09-28 21:21
If you're seeing the following error(s):
`$ npx degit https://github.com/sveltejs/sapper-template#rollup my-app

! could not find commit hash for rollup`

or

`$ npx degit https://github.com/sveltejs/sapper-template#webpack my-app

! could not find commit hash for webpack`

It's because git isn't working. git depends on xcode and xcode requires you to accept it's license agreement.

Try running "git" and if you see the following message:
`$ git
Agreeing to the Xcode/iOS license requires admin privileges, please run “sudo xcodebuild -license” and then retry this command.`
then type:
`sudo xcodebuild -license` and follow instructions for scrolling through the license agreement. At the end, you will need to type "agree" then <enter>
At that point, your original command should work fine.

**Comment by masterl** [comment] 2019-10-07 00:22
I have the same error with sveltejs/template.

Doc said to just run `degit sveltejs/template svelte-app`

Results:

```
$ degit sveltejs/template svelte-app
! could not find commit hash for master
```
---
| What | Version |
|---       |---          |
| Linux Manjaro | 18.1.0 Juhraya |
| Git | 2.23.0 |
| Node | 12.9.1 |
| NPM | 6.11.2 |
| Degit | 2.1.4 | 


I use git everyday without any problems.
Cloning the [svelte template repo](https://github.com/sveltejs/template) manually works without problems.

**Comment by vguhesan** [comment] 2019-10-07 02:05
@masterl did you try what I have suggested above?
https://github.com/Rich-Harris/degit/issues/37#issuecomment-536226465

**Comment by masterl** [comment] 2019-10-08 02:42
@vguhesan That doesn't apply.
I'm neither on mac, nor don't have git installed and configured.

Everything is on the comment, I have git, node, npm, degit all installed.
As I also said above, I can clone the repo directly without any problems.

The issue seems to be on degit itself.

**Comment by paulocoghi** [comment] 2019-10-08 12:32
@masterl , can you try again with `cache: false` ?

**Comment by masterl** [comment] 2019-10-09 00:04
@paulocoghi Where do I use that?

running `degit --help` the cache option doesn't even has a parameter:
`--cache, -c Only use local cache`

**Comment by paulocoghi** [comment] 2019-10-09 01:31
@masterl , unfortunately you are right.

As mentioned by @cogoo and @riazXrazor, when using degit on code (not as cli), setting `cache` to `false` on the options may solve this problem 

But it seems that we can't do the same on cli.

**Comment by PlkMarudny** [comment] 2019-11-03 11:13
So, how to disable  caching in degit?

**Comment by paulocoghi** [comment] 2019-11-04 14:00
@PlkMarudny , this way:

```js
degit(<repo_url>, {
    cache: false
});
```

**Comment by rollingw** [comment] 2019-11-16 13:21
Had the same issue ... it was a certificate related issue:
https://confluence.atlassian.com/bitbucketserverkb/ssl-certificate-problem-unable-to-get-local-issuer-certificate-816521128.html
wget the right one, copy to  /bin, and adjust .gitconfig in home.  Worked for me

**Comment by Conduitry** [comment] 2019-12-29 23:24
I was just looking into getting degit to display more helpful error messages when it runs into a problem, and I found that it _does_ display the underlying error if you call it with the verbose `-v` flag. Does it make sense to always display that error? I'm hoping that will eliminate a lot of questions in Svelte issues and the chatroom about this. In the meantime, now that I know this, I suppose we can tell people to run it again with `-v` so we can get some sort of idea of what's happening.

**Comment by thinkOfaNumber** [comment] 2020-02-10 05:27
I know this thread is covering a lot of different issues now, but I had the same "could not fetch remote":

    npx degit "sveltejs/sapper-template#webpack" sapper-test
    ! could not fetch remote https://github.com/sveltejs/sapper-template
    ! could not find commit hash for webpack

but it turns out that my .gitconfig in my home directory had an invalid http proxy that I could no longer access. Hope this helps someone.

**Comment by bernardoadc** [comment] 2020-02-12 12:56
> Would be interesting if `degit` doesn't depend on `git` to work. I was trying to figure out for weeks why some team mates had the same issue. 😄

What if degit supports cloning local repos? That wouldn't work. I think we should properly display error messages so people can act to solve problems, not dodge them

**Comment by paulocoghi** [comment] 2020-02-14 12:13
@bernardoadc , you are right :+1: I had not thought about this possibility and, in this case, it is interesting that `degit` uses `git`.

Since `gittar` is a good alternative when all you want is to clone public repos, I believe that we have good options for any case.

**Comment by hypersundays** [comment] 2020-08-12 04:20
> I know this thread is covering a lot of different issues now, but I had the same "could not fetch remote":
> 
> ```
> npx degit "sveltejs/sapper-template#webpack" sapper-test
> ! could not fetch remote https://github.com/sveltejs/sapper-template
> ! could not find commit hash for webpack
> ```
> 
> but it turns out that my .gitconfig in my home directory had an invalid http proxy that I could no longer access. Hope this helps someone.

I was getting this same error trying to run `degit` through `npx`. Once I installed `degit` globally, everything worked like a charm

**Comment by EitharAlotoom95** [comment] 2020-10-24 21:01
I run this "degit sveltejs/template my-svelte-project" on git terminal not the cmd .. and it works .
just right click then choose git bash here and run the command there . I hope that will be helpful .

**Comment by rdela** [comment] 2020-11-23 19:30
fregante's mention above of #242/#207 helped me figure my encounter with this error message out
when I ran it with the `-v` option per Conduitry's suggestion I got: `> destination directory is empty`, not helpful.
but the problem was I needed to append the branch, `#trunk` in this case, because this repo does not have a `master` branch.

**Comment by netaisllc** [comment] 2020-12-05 23:07
Note that **Github** itself has seemingly begun to default new repos to a `main` branch.  

Today I ran into what looked like a `degit` issue (_! could not find commit hash for master_) which actually wasn't `degit`'s problem. There indeed wasn't a `master` branch. As soon as I created one and ran `degit` again there was much joy.

**Comment by paulocoghi** [comment] 2020-12-06 19:25
A PR adding a check to see which branch is available between `main` and `master` can solve the scenario mentioned by @netaisllc .

**Closed** 2021-03-31 15:45 UTC

**Comment by rajeeshsays** [comment] 2021-08-12 09:43
D:\ANZ104AngularDemo\ANZ104AngularDemo\angular\taskbox>degit chromaui/intro-storybook-angular-template
! could not fetch remote https://github.com/chromaui/intro-storybook-angular-template
! could not find commit hash for HEAD
Pls give a solution...

**Comment by rdela** [comment] 2021-08-12 17:35
hi @rajeeshsays, please open an issue on [the repository in question](https://github.com/chromaui/intro-storybook-angular-template), as:

```shell
npx degit chromaui/intro-storybook-svelte-template taskbox
```

from [intro-storybook-svelte-template](https://github.com/chromaui/intro-storybook-svelte-template) works fine, and the command that you presumably ran correctly in a supported environment is in their readme:

```shell
npx degit chromaui/intro-storybook-angular-template taskbox
```

**Comment by wangjia184** [comment] 2021-12-22 00:41
installed the latest git version 2.34.1.windows.1

Failed with same error

**Comment by glayn2bukman** [comment] 2022-09-23 15:35
turns out the github repo is at `sveltejs/template` not `svelte/template` and as such the command should be
`npx degit sveltejs/template <your-project-name>`

**Comment by pixelbadger01** [comment] 2023-10-15 23:32
Hello.  I am getting this error: 

' degit radixdlt/create-scrypto-dapp
! could not download https://github.com/radixdlt/create-scrypto-dapp/archive/75feed25fadafa73dbd8349974d755087afd44b3.tar.gz '

I took the liberty of checking the comments before me, and I can confirm Git is working so I'm just wondering what else I can look into.  

Yes the URL is also fine.

**Comment by paulocoghi** [comment] 2023-10-16 08:12
> ... it does display the underlying error if you call it with the verbose `-v` flag

For @NateDawg360 and everyone else: please use `-v` (verbose mode) to display the root cause, as already explained on the thread by Conduitry

**Comment by vdawg-git** [comment] 2023-11-11 22:07
I am also getting this error while using the JS Api I am on Arch Linux, with git installed.
Setting `cache` to false, solves this.
Enabling `verbose` does not result in a more descriptive error.

Its the error in the title + that it cannot find the commit hash of the repo
