### ISSUE TITLE
Default to "main" branch

### ISSUE THREAD

**Issue by Skayo** [Rich-Harris/degit#242] opened 2020-11-20 01:30 UTC
New GitHub projects are now using a "main" branch instead of the "master" branch.
`degit` should sooner or later support this new behaviour.

As of now, I get this error:
```
! could not find commit hash for master
```
And I have to specify the branch manually (append `#main`)

**Comment by fregante** [comment] 2020-11-21 02:20
Duplicate of #37

**Closed** 2021-03-31 15:45 UTC
